import React, { ReactNode, useEffect, useState } from "react";
import { Button, Modal } from "antd";
import axios from "axios";
import styles from "@/app/page.module.css";
import { CredentialResponse, GoogleLogin } from "@react-oauth/google";
import { User } from "@/types";

const SignInButton = ({
  children,
  onAutoSignInSuccess,
  onClickSignInSuccess,
  size,
}: {
  children: ReactNode;
  // eslint-disable-next-line no-unused-vars
  onAutoSignInSuccess: (data: User) => void;
  // eslint-disable-next-line no-unused-vars
  onClickSignInSuccess: (data: User) => void;
  size: "large" | "middle" | "small";
}) => {
  const [signInModalOpen, setSignInModalOpen] = useState(false);

  const getUserInfo = async () => {
    const res = await axios.get("http://localhost:8088/user/info");
    if (res?.data) {
      return res.data;
    }
    return null;
  };
  useEffect(() => {
    getUserInfo()
      .then((res) => {
        onAutoSignInSuccess(res);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);

  const onLoginSuccess = async (credentialResponse: CredentialResponse) => {
    console.log(credentialResponse);
    try {
      const res = await axios.post("http://localhost:8088/user/verify", {
        credential: credentialResponse.credential,
      });

      console.log(res.data);
      const token = res.data; // token generated by server
      localStorage.setItem("token", token);
      setSignInModalOpen(false);
      getUserInfo().then((res) => {
        onClickSignInSuccess(res);
      });
    } catch (error) {
      console.error("Login Error:", error);
    }
  };

  const onLoginError = () => {
    console.log("Login Error.");
  };

  const showSignInModal = () => {
    setSignInModalOpen(true);
  };

  const closeSignInModal = () => {
    setSignInModalOpen(false);
  };

  return (
    <div>
      <Button type="primary" size={size} onClick={showSignInModal}>
        {children}
      </Button>

      <Modal open={signInModalOpen} onCancel={closeSignInModal} footer="">
        <div className={styles.signInModal}>
          <GoogleLogin
            onSuccess={onLoginSuccess}
            onError={onLoginError}
            useOneTap
          />
        </div>
      </Modal>
    </div>
  );
};

export default SignInButton;
